/* Countries.js
 * This list simply provides a json
 * list of countries along with their
 * alpha-3 code (as defined in ISO-3166)
 */

var backEnd = backEnd || {};

backEnd.countryList = [
	new types.Country("Afghanistan","AFG", 33, 65),
	new types.Country("Åland Islands","ALA", 0, 0),
	new types.Country("Albania","ALB", 0, 0),
	new types.Country("Algeria","DZA", 0, 0),
	new types.Country("American Samoa","ASM", 0, 0),
	new types.Country("Andorra","AND", 0, 0),
	new types.Country("Angola","AGO", 0, 0),
	new types.Country("Anguilla","AIA", 0, 0),
	new types.Country("Antarctica","ATA", 0, 0),
	new types.Country("Antigua and Barbuda","ATG", 0, 0),
	new types.Country("Argentina","ARG", 0, 0),
	new types.Country("Armenia","ARM", 0, 0),
	new types.Country("Aruba","ABW", 0, 0),
	new types.Country("Australia","AUS", 0, 0),
	new types.Country("Austria","AUT", 0, 0),
	new types.Country("Azerbaijan","AZE", 0, 0),
	new types.Country("Bahamas","BHS", 0, 0),
	new types.Country("Bahrain","BHR", 0, 0),
	new types.Country("Bangladesh","BGD", 0, 0),
	new types.Country("Barbados","BRB", 0, 0),
	new types.Country("Belarus","BLR", 0, 0),
	new types.Country("Belgium","BEL", 0, 0),
	new types.Country("Belize","BLZ", 0, 0),
	new types.Country("Benin","BEN", 0, 0),
	new types.Country("Bermuda","BMU", 0, 0),
	new types.Country("Bhutan","BTN", 0, 0),
	new types.Country("Bolivia","BOL", 0, 0),
	new types.Country("Bonaire, Sint Eustatius and Saba","BES", 0, 0),
	new types.Country("Bosnia and Herzegovina","BIH", 0, 0),
	new types.Country("Botswana","BWA", 0, 0),
	new types.Country("Bouvet Island","BVT", 0, 0),
	new types.Country("Brazil","BRA", 0, 0),
	new types.Country("British Indian Ocean Territory","IOT", 0, 0),
	new types.Country("Brunei Darussalam","BRN", 0, 0),
	new types.Country("Bulgaria","BGR", 0, 0),
	new types.Country("Burkina Faso","BFA", 0, 0),
	new types.Country("Burundi","BDI", 0, 0),
	new types.Country("Cambodia","KHM", 0, 0),
	new types.Country("Cameroon","CMR", 0, 0),
	new types.Country("Canada","CAN", 0, 0),
	new types.Country("Cape Verde","CPV", 0, 0),
	new types.Country("Cayman Islands","CYM", 0, 0),
	new types.Country("Central African Republic","CAF", 0, 0),
	new types.Country("Chad","TCD", 0, 0),
	new types.Country("Chile","CHL", 0, 0),
	new types.Country("China","CHN", 0, 0),
	new types.Country("Christmas Island","CXR", 0, 0),
	new types.Country("Cocos (Keeling) Islands","CCK", 0, 0),
	new types.Country("Colombia","COL", 0, 0),
	new types.Country("Comoros","COM", 0, 0),
	new types.Country("Congo","COG", 0, 0),
	new types.Country("Congo, the Democratic Republic of the","COD", 0, 0),
	new types.Country("Cook Islands","COK", 0, 0),
	new types.Country("Costa Rica","CRI", 0, 0),
	new types.Country("Côte d'Ivoire","CIV", 0, 0),
	new types.Country("Croatia","HRV", 0, 0),
	new types.Country("Cuba","CUB", 0, 0),
	new types.Country("Curaçao","CUW", 0, 0),
	new types.Country("Cyprus","CYP", 0, 0),
	new types.Country("Czech Republic","CZE", 0, 0),
	new types.Country("Denmark","DNK", 0, 0),
	new types.Country("Djibouti","DJI", 0, 0),
	new types.Country("Dominica","DMA", 0, 0),
	new types.Country("Dominican Republic","DOM", 0, 0),
	new types.Country("Ecuador","ECU", 0, 0),
	new types.Country("Egypt","EGY", 0, 0),
	new types.Country("El Salvador","SLV", 0, 0),
	new types.Country("Equatorial Guinea","GNQ", 0, 0),
	new types.Country("Eritrea","ERI", 0, 0),
	new types.Country("Estonia","EST", 0, 0),
	new types.Country("Ethiopia","ETH", 0, 0),
	new types.Country("Falkland Islands (Malvinas)","FLK", 0, 0),
	new types.Country("Faroe Islands","FRO", 0, 0),
	new types.Country("Fiji","FJI", 0, 0),
	new types.Country("Finland","FIN", 0, 0),
	new types.Country("France","FRA", 0, 0),
	new types.Country("French Guiana","GUF", 0, 0),
	new types.Country("French Polynesia","PYF", 0, 0),
	new types.Country("French Southern Territories","ATF", 0, 0),
	new types.Country("Gabon","GAB", 0, 0),
	new types.Country("Gambia","GMB", 0, 0),
	new types.Country("Georgia","GEO", 0, 0),
	new types.Country("Germany","DEU", 0, 0),
	new types.Country("Ghana","GHA", 0, 0),
	new types.Country("Gibraltar","GIB", 0, 0),
	new types.Country("Greece","GRC", 0, 0),
	new types.Country("Greenland","GRL", 0, 0),
	new types.Country("Grenada","GRD", 0, 0),
	new types.Country("Guadeloupe","GLP", 0, 0),
	new types.Country("Guam","GUM", 0, 0),
	new types.Country("Guatemala","GTM", 0, 0),
	new types.Country("Guernsey","GGY", 0, 0),
	new types.Country("Guinea","GIN", 0, 0),
	new types.Country("Guinea-Bissau","GNB", 0, 0),
	new types.Country("Guyana","GUY", 0, 0),
	new types.Country("Haiti","HTI", 0, 0),
	new types.Country("Heard Island and McDonald Islands","HMD", 0, 0),
	new types.Country("Holy See (Vatican City State)","VAT", 0, 0),
	new types.Country("Honduras","HND", 0, 0),
	new types.Country("Hong Kong","HKG", 0, 0),
	new types.Country("Hungary","HUN", 0, 0),
	new types.Country("Iceland","ISL", 0, 0),
	new types.Country("India","IND", 0, 0),
	new types.Country("Indonesia","IDN", 0, 0),
	new types.Country("Iran, Islamic Republic of","IRN", 0, 0),
	new types.Country("Iraq","IRQ", 0, 0),
	new types.Country("Ireland","IRL", 0, 0),
	new types.Country("Isle of Man","IMN", 0, 0),
	new types.Country("Israel","ISR", 0, 0),
	new types.Country("Italy","ITA", 0, 0),
	new types.Country("Jamaica","JAM", 0, 0),
	new types.Country("Japan","JPN", 0, 0),
	new types.Country("Jersey","JEY", 0, 0),
	new types.Country("Jordan","JOR", 0, 0),
	new types.Country("Kazakhstan","KAZ", 0, 0),
	new types.Country("Kenya","KEN", 0, 0),
	new types.Country("Kiribati","KIR", 0, 0),
	new types.Country("Korea, Democratic People's Republic of","PRK", 0, 0),
	new types.Country("Korea, Republic of","KOR", 0, 0),
	new types.Country("Kuwait","KWT", 0, 0),
	new types.Country("Kyrgyzstan","KGZ", 0, 0),
	new types.Country("Lao People's Democratic Republic","LAO", 0, 0),
	new types.Country("Latvia","LVA", 0, 0),
	new types.Country("Lebanon","LBN", 0, 0),
	new types.Country("Lesotho","LSO", 0, 0),
	new types.Country("Liberia","LBR", 0, 0),
	new types.Country("Libya","LBY", 0, 0),
	new types.Country("Liechtenstein","LIE", 0, 0),
	new types.Country("Lithuania","LTU", 0, 0),
	new types.Country("Luxembourg","LUX", 0, 0),
	new types.Country("Macao","MAC", 0, 0),
	new types.Country("Macedonia","MKD", 0, 0),
	new types.Country("Madagascar","MDG", 0, 0),
	new types.Country("Malawi","MWI", 0, 0),
	new types.Country("Malaysia","MYS", 0, 0),
	new types.Country("Maldives","MDV", 0, 0),
	new types.Country("Mali","MLI", 0, 0),
	new types.Country("Malta","MLT", 0, 0),
	new types.Country("Marshall Islands","MHL", 0, 0),
	new types.Country("Martinique","MTQ", 0, 0),
	new types.Country("Mauritania","MRT", 0, 0),
	new types.Country("Mauritius","MUS", 0, 0),
	new types.Country("Mayotte","MYT", 0, 0),
	new types.Country("Mexico","MEX", 0, 0),
	new types.Country("Micronesia, Federated States of","FSM", 0, 0),
	new types.Country("Moldova","MDA", 0, 0),
	new types.Country("Monaco","MCO", 0, 0),
	new types.Country("Mongolia","MNG", 0, 0),
	new types.Country("Montenegro","MNE", 0, 0),
	new types.Country("Montserrat","MSR", 0, 0),
	new types.Country("Morocco","MAR", 0, 0),
	new types.Country("Mozambique","MOZ", 0, 0),
	new types.Country("Myanmar","MMR", 0, 0),
	new types.Country("Namibia","NAM", 0, 0),
	new types.Country("Nauru","NRU", 0, 0),
	new types.Country("Nepal","NPL", 0, 0),
	new types.Country("Netherlands","NLD", 0, 0),
	new types.Country("New Caledonia","NCL", 0, 0),
	new types.Country("New Zealand","NZL", 0, 0),
	new types.Country("Nicaragua","NIC", 0, 0),
	new types.Country("Niger","NER", 0, 0),
	new types.Country("Nigeria","NGA", 0, 0),
	new types.Country("Niue","NIU", 0, 0),
	new types.Country("Norfolk Island","NFK", 0, 0),
	new types.Country("Northern Mariana Islands","MNP", 0, 0),
	new types.Country("Norway","NOR", 0, 0),
	new types.Country("Oman","OMN", 0, 0),
	new types.Country("Pakistan","PAK", 0, 0),
	new types.Country("Palau","PLW", 0, 0),
//	new types.Country("Palestine, State of","PSE", 0, 0),
	new types.Country("Panama","PAN", 0, 0),
	new types.Country("Papua New Guinea","PNG", 0, 0),
	new types.Country("Paraguay","PRY", 0, 0),
	new types.Country("Peru","PER", 0, 0),
	new types.Country("Philippines","PHL", 0, 0),
	new types.Country("Pitcairn","PCN", 0, 0),
	new types.Country("Poland","POL", 0, 0),
	new types.Country("Portugal","PRT", 0, 0),
	new types.Country("Puerto Rico","PRI", 0, 0),
	new types.Country("Qatar","QAT", 0, 0),
	new types.Country("Réunion","REU", 0, 0),
	new types.Country("Romania","ROU", 0, 0),
	new types.Country("Russian Federation","RUS", 0, 0),
	new types.Country("Rwanda","RWA", 0, 0),
	new types.Country("Saint Barthélemy","BLM", 0, 0),
	new types.Country("Saint Helena","SHN", 0, 0),
	new types.Country("Saint Kitts and Nevis","KNA", 0, 0),
	new types.Country("Saint Lucia","LCA", 0, 0),
	new types.Country("Saint Martin (French part)","MAF", 0, 0),
	new types.Country("Saint Pierre and Miquelon","SPM", 0, 0),
	new types.Country("Saint Vincent and the Grenadines","VCT", 0, 0),
	new types.Country("Samoa","WSM", 0, 0),
	new types.Country("San Marino","SMR", 0, 0),
	new types.Country("Sao Tome and Principe","STP", 0, 0),
	new types.Country("Saudi Arabia","SAU", 0, 0),
	new types.Country("Senegal","SEN", 0, 0),
	new types.Country("Serbia","SRB", 0, 0),
	new types.Country("Seychelles","SYC", 0, 0),
	new types.Country("Sierra Leone","SLE", 0, 0),
	new types.Country("Singapore","SGP", 0, 0),
	new types.Country("Sint Maarten","SXM", 0, 0),
	new types.Country("Slovakia","SVK", 0, 0),
	new types.Country("Slovenia","SVN", 0, 0),
	new types.Country("Solomon Islands","SLB", 0, 0),
	new types.Country("Somalia","SOM", 0, 0),
	new types.Country("South Africa","ZAF", 0, 0),
	new types.Country("South Georgia and the South Sandwich Islands","SGS", 0, 0),
	new types.Country("South Sudan","SSD", 0, 0),
	new types.Country("Spain","ESP", 0, 0),
	new types.Country("Sri Lanka","LKA", 0, 0),
	new types.Country("Sudan","SDN", 0, 0),
	new types.Country("Suriname","SUR", 0, 0),
	new types.Country("Svalbard and Jan Mayen","SJM", 0, 0),
	new types.Country("Swaziland","SWZ", 0, 0),
	new types.Country("Sweden","SWE", 0, 0),
	new types.Country("Switzerland","CHE", 0, 0),
	new types.Country("Syrian Arab Republic","SYR", 0, 0),
	new types.Country("Taiwan","TWN", 0, 0),
	new types.Country("Tajikistan","TJK", 0, 0),
	new types.Country("Tanzania, United Republic of","TZA", 0, 0),
	new types.Country("Thailand","THA", 0, 0),
	new types.Country("Timor-Leste","TLS", 0, 0),
	new types.Country("Togo","TGO", 0, 0),
	new types.Country("Tokelau","TKL", 0, 0),
	new types.Country("Tonga","TON", 0, 0),
	new types.Country("Trinidad and Tobago","TTO", 0, 0),
	new types.Country("Tunisia","TUN", 0, 0),
	new types.Country("Turkey","TUR", 0, 0),
	new types.Country("Turkmenistan","TKM", 0, 0),
	new types.Country("Turks and Caicos Islands","TCA", 0, 0),
	new types.Country("Tuvalu","TUV", 0, 0),
	new types.Country("Uganda","UGA", 0, 0),
	new types.Country("Ukraine","UKR", 0, 0),
	new types.Country("United Arab Emirates","ARE", 0, 0),
	new types.Country("United Kingdom","GBR", 0, 0),
	new types.Country("United States","USA", 38, -97),
	new types.Country("United States Minor Outlying Islands","UMI", 0, 0),
	new types.Country("Uruguay","URY", 0, 0),
	new types.Country("Uzbekistan","UZB", 0, 0),
	new types.Country("Vanuatu","VUT", 0, 0),
	new types.Country("Venezuela","VEN", 0, 0),
	new types.Country("Viet Nam","VNM", 0, 0),
	new types.Country("Virgin Islands, British","VGB", 0, 0),
	new types.Country("Virgin Islands, U.S.","VIR", 0, 0),
	new types.Country("Wallis and Futuna","WLF", 0, 0),
	new types.Country("Western Sahara","ESH", 0, 0),
	new types.Country("Yemen","YEM", 0, 0),
	new types.Country("Zambia","ZMB", 0, 0),
	new types.Country("Zimbabwe","ZWE", 0, 0)
];

backEnd.countryDict = {};

for (var i = 0; i < backEnd.countryList.length; i++) {
	var country = backEnd.countryList[i]
	backEnd.countryDict[country.name] = country
};